// <auto-generated />
using System;
using ControlGastosBlazor.Components.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlGastosBlazor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250602071657_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlGastosBlazor.Components.Entities.Deposito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("FondoMonetarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FondoMonetarioId");

                    b.ToTable("Depositos");
                });

            modelBuilder.Entity("ControlGastosBlazor.Components.Entities.FondoMonetario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fondos");
                });

            modelBuilder.Entity("ControlGastosBlazor.Components.Entities.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comercio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("FondoMonetarioId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FondoMonetarioId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("ControlGastosBlazor.Components.Entities.GastoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GastoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoGastoCodigo")
                        .HasColumnType("int");

                    b.Property<int?>("TipoGastoid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GastoId");

                    b.HasIndex("TipoGastoid");

                    b.ToTable("GastoDetalles");
                });

            modelBuilder.Entity("ControlGastosBlazor.Components.Entities.Presupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoGastoCodigo")
                        .HasColumnType("int");

                    b.Property<int?>("TipoGastoid")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TipoGastoid");

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("ControlGastosBlazor.Components.Entities.TipoGasto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TipoGastos");
                });

            modelBuilder.Entity("ControlGastosBlazor.Components.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ControlGastosBlazor.Components.Entities.Deposito", b =>
                {
                    b.HasOne("ControlGastosBlazor.Components.Entities.FondoMonetario", "Fondo")
                        .WithMany()
                        .HasForeignKey("FondoMonetarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fondo");
                });

            modelBuilder.Entity("ControlGastosBlazor.Components.Entities.Gasto", b =>
                {
                    b.HasOne("ControlGastosBlazor.Components.Entities.FondoMonetario", "Fondo")
                        .WithMany()
                        .HasForeignKey("FondoMonetarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fondo");
                });

            modelBuilder.Entity("ControlGastosBlazor.Components.Entities.GastoDetalle", b =>
                {
                    b.HasOne("ControlGastosBlazor.Components.Entities.Gasto", "Gasto")
                        .WithMany("Detalles")
                        .HasForeignKey("GastoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlGastosBlazor.Components.Entities.TipoGasto", "TipoGasto")
                        .WithMany()
                        .HasForeignKey("TipoGastoid");

                    b.Navigation("Gasto");

                    b.Navigation("TipoGasto");
                });

            modelBuilder.Entity("ControlGastosBlazor.Components.Entities.Presupuesto", b =>
                {
                    b.HasOne("ControlGastosBlazor.Components.Entities.TipoGasto", "TipoGasto")
                        .WithMany()
                        .HasForeignKey("TipoGastoid");

                    b.Navigation("TipoGasto");
                });

            modelBuilder.Entity("ControlGastosBlazor.Components.Entities.Gasto", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
